version: "3.7"
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - .env_prod

  app:
    build:
      context: .
    env_file:
      - .env_prod
    container_name: warehouse_app
    command: ["/warehouse/docker/app.sh"]
    ports:
      - 80:8000
    depends_on:
      - db
